accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    RegisterFormView,
    UserProfileView,
    UserPostsView,
    UserUpdateView,
    UserDeleteView,
    )

app_name = 'accounts'

urlpatterns = [
    path('login/'                  , LoginView.as_view()          , name='login'),
    path('logout/'                 , LogoutView.as_view()         , name='logout'),
    path('register/'               , RegisterFormView.as_view()   , name='register'),
    path('profile/'                , UserProfileView.as_view()    , name='profile'),
    path('profile/change-password/', PasswordChangeView.as_view() , name='change_password'),
    path('profile/update/'         , UserUpdateView.as_view()     , name='update'),
    path('profile/delete/'         , UserDeleteView.as_view()     , name='delete'),
    path('posts/'                  , UserPostsView.as_view()      , name='posts'),
]

blog/urls.py
from django.urls import path

from .views import (
    PostListView,
    PostByCommentsListView,
    PostByLastCommentListView,
    PostByViewsListView,
    PostByRatingListView,
    PostDetailView,
    PostLikeRedirectView,
    PostDislikeRedirectView,
    CommentCreateView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    TagCreateView,
    TagListView,
    PostByTagListView
    )

app_name = 'blog'

urlpatterns = [
    path(''                             , PostListView.as_view()           , name='index'),
    path('most-commented/'              , PostByCommentsListView.as_view() , name='most_commented'),
    path('last-commented/'              , PostByLastCommentListView.as_view(), name='last_commented'),
    path('most-viewed/'                 , PostByViewsListView.as_view()    , name='most_viewed'),
    path('rating/'                      , PostByRatingListView.as_view()   , name='rating'),
    path('post/add/'                    , PostCreateView.as_view()         , name='post_create'),
    path('post/<slug:slug>/'            , PostDetailView.as_view()         , name='post_detail'),
    path('post/<slug:slug>/update/'     , PostUpdateView.as_view()         , name='post_update'),
    path('post/<slug:slug>/delete/'     , PostDeleteView.as_view()         , name='post_delete'),
    path('post/<slug:slug>/like/'       , PostLikeRedirectView.as_view()   , name='post_like'),
    path('post/<slug:slug>/dislike/'    , PostDislikeRedirectView.as_view(), name='post_dislike'),
    path('post/<slug:slug>/comment/add/', CommentCreateView.as_view()      , name='comment_add'),
    # path('tag/'                         , TagListView.as_view()            , name='tags'),
    # path('tag/add/'                     , TagCreateView.as_view()          , name='tag_add'),
    path('tag/<slug:slug>/'             , PostByTagListView.as_view()      , name='tag_detail'),
]

simpleblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(''         , include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/'   , admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

blog/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

from pytils.translit import slugify


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    pub_date = models.DateTimeField('publication date', auto_now_add=True)
    upd_date = models.DateTimeField('update date', auto_now=True)
    text = models.TextField()
    comments = models.PositiveSmallIntegerField(default=0)
    last_comment_date = models.DateTimeField(default=datetime(1,1,1,0,0))
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveSmallIntegerField(default=0)
    dislikes = models.PositiveSmallIntegerField(default=0)
    rating = models.SmallIntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    tags = models.ManyToManyField('Tag')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True, verbose_name='Фото')
    slug = models.SlugField(unique=True)

    class Meta:
        db_table = 'posts'
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        ordering = ['-upd_date']

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.rating = self.likes - self.dislikes
        super().save(*args, **kwargs)

    def __str__(self):
        return '{} by {}'.format(self.title[:15], self.author)

    def get_image(self):
        if self.photo:
            return self.photo.url
        else:
            return 'https://fakeimg.pl/300x200/?text=Fake%20Img&font=lobster'


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    pub_date = models.DateTimeField('publication date', auto_now_add=True)
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        db_table = 'comments'
        ordering = ['-pub_date']

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.post.id})

    def __str__(self):
        return '{} by {}'.format(self.text[:15], self.author)


class Tag(models.Model):
    DEFAULT = 'default'
    PRIMARY = 'primary'
    SUCCESS = 'success'
    INFO = 'info'
    WARNING = 'warning'
    DANGER = 'danger'
    TAG_COLOR_CHOICES = (
        (DEFAULT, 'White'),
        (PRIMARY, 'Blue'),
        (SUCCESS, 'Green'),
        (INFO, 'Light blue'),
        (WARNING, 'Yellow'),
        (DANGER, 'Red')
    )
    color = models.CharField(max_length=10,
                             choices=TAG_COLOR_CHOICES,
                             default=DEFAULT)
    title = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(unique=True)

    class Meta:
        db_table = 'tags'
        ordering = ['title']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.title)


class View(models.Model):
    remote_addr = models.CharField(max_length=20)
    date_viewed = models.DateField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        db_table = 'views'

    def __str__(self):
        return '{} on {} from {}'.format(self.post, self.remote_addr, self.date_viewed)


class Button(models.Model):
    is_liked = models.BooleanField()
    is_disliked = models.BooleanField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'buttons'

    def __str__(self):
        return '{} to {}'.format(self.user, self.post.title[:15])

accounts/forms.py
from django.forms import ModelForm

from django.contrib.auth.models import User


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import (
    AuthenticationForm,
    PasswordChangeForm, 
    UserCreationForm,
    UserChangeForm
    )
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.views.generic.base import View
from django.views.generic import FormView, RedirectView, TemplateView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse

from .forms import UserForm


class RegisterFormView(FormView):
    template_name = 'accounts/register.html'
    form_class = UserCreationForm
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        new_user = form.save()
        username = new_user.username
        password = form.cleaned_data['password1']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super().form_valid(form)


class LoginView(FormView):
    template_name = 'accounts/login.html'
    form_class = AuthenticationForm
    success_url = reverse_lazy('accounts:profile')

    def form_valid(self, form):
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return super().form_valid(form)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('blog:index')


class PasswordChangeView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/password_change.html'
    form_class = PasswordChangeForm
    
    def get(self, request, *args, **kwargs):
        form = self.form_class(self.request.user)
        return render(request, self.template_name, {'form': form})
        
    def post(self, request, *args, **kwargs):
        form = self.form_class(self.request.user, data=request.POST)
        if form.is_valid():
            form.save()
            username = self.request.user.username
            password = form.cleaned_data['new_password1']
            user = authenticate(username=username, password=password)
            login(self.request, user)
            messages.success(request, 'Password updated.')
            return redirect('accounts:profile')
        return render(request, self.template_name, {'form': form})


class UserProfileView(TemplateView):
    template_name = 'accounts/profile.html'


class UserPostsView(TemplateView):
    template_name = 'accounts/user_posts.html'


class UserUpdateView(LoginRequiredMixin, TemplateView):
    template_name = 'accounts/profile.html'
    form_class = UserForm

    def get(self, request, *args, **kwargs):
        form = self.form_class(instance=self.request.user)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(instance=self.request.user, data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Profile updated.')
            return redirect('accounts:profile')
        return render(request, self.template_name, {'form': form})


class UserDeleteView(LoginRequiredMixin, RedirectView):
    pattern_name = 'blog:index'

    def post(self, request, *args, **kwargs):
        request.user.delete()
        messages.success(request, 'User deleted.')
        return super().post(request, *args, **kwargs)

accounts/templates/accounts/login.html
{% extends "blog/layouts/base.html" %}

{% block title %}Login{% endblock %}

{% block content %}
  <div class="leave-comment mr0"><!--leave comment-->
      <h3 class="text-uppercase">Login</h3>
      <br>
      <form class="form-horizontal contact-form" role="form" method="post" action="">
          {% csrf_token %}
          <div class="form-group">
              <div class="col-md-12">
                  <input 
                      type="text" 
                      class="form-control" 
                      id="username" 
                      name="username"
                      placeholder="Username">
              </div>
          </div>
          <div class="form-group">
              <div class="col-md-12">
                  <input 
                      type="text" 
                      class="form-control" 
                      id="password" 
                      name="password"
                      placeholder="password">
              </div>
          </div>
          <button type="submit" name="submit" class="btn send-btn">Login</button>
      </form>
  </div><!--end leave comment-->
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends "blog/base.html" %}
{% load bootstrap3 %}

{% block title %}Password change{% endblock %}

{% block content %}
<h3>Password change</h3>
<form action="" method="post" class="form" role="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-success">Password change</button>
</form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends "blog/layouts/base.html" %}
{% load static %}

{% block title %}{{ request.user.username }}{% endblock %}

{% block content %}
<div class="leave-comment mr0"><!--leave comment-->
    <h3 class="text-uppercase">{{ request.user.username|capfirst }}</h3>
    <br>
    <img src="assets/images/abc.jpg" alt="" class="profile-image">
    <form class="form-horizontal contact-form" role="form" method="post" action="{% url 'accounts:update' %}">
        <div class="form-group">
            <div class="col-md-12">
                <input 
                    type="text" 
                    class="form-control" 
                    id="first_name" 
                    name="first_name"
                    value="{{ request.user.first_name }}"
                    placeholder="First name"
                >
                {{ form.first_name.errors }}
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <input 
                    type="text" 
                    class="form-control" 
                    id="last_name" 
                    name="last_name"
                    value="{{ request.user.last_name }}"
                    placeholder="Last name"
                >
                {{ form.last_name.errors }}
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <input 
                    type="email" 
                    class="form-control" 
                    id="email" 
                    name="email"
                    value="{{ request.user.email }}"
                    placeholder="Email"
                >
                {{ form.email.errors }}
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <input 
                    type="password" 
                    class="form-control" 
                    id="password" 
                    name="password1"
                    placeholder="Password"
                >
                {{ form.password1.errors }}
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <input 
                    type="password" 
                    class="form-control" 
                    id="password" 
                    name="password2"
                    placeholder="Confirm password"
                >
                {{ form.password2.errors }}
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <input type="file" class="form-control" id="image" name="image">	
            </div>
        </div>
        <button type="submit" name="submit" class="btn send-btn">Save</button>
        <form action="{% url 'accounts:delete' %}" method="post">
            {% csrf_token %}
            <button type="submit" onclick="return confirm('Are you sure?')" class="btn send-btn">Delete</button>
        </form>
    </form>
</div><!--end leave comment-->
{% endblock %}

accounts/templates/accounts/register.html
{% extends "blog/layouts/base.html" %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="leave-comment mr0"><!--leave comment-->
    <h3 class="text-uppercase">Register</h3>
    <br>
    <form class="form-horizontal contact-form" role="form" method="post" action="">
        {% csrf_token %}
        <div class="form-group">
            <div class="col-md-12">
                <input 
                    type="text" 
                    class="form-control" 
                    id="username" 
                    name="username"
                    placeholder="Username"
                >
                {{ form.username.errors }}  
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <input 
                  type="password" 
                  class="form-control" 
                  id="password" 
                  name="password1"
                  placeholder="Password"
                >
                {{ form.password1.errors }}
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                <input 
                  type="password" 
                  class="form-control" 
                  id="password" 
                  name="password2"
                  placeholder="Confirm password"
                >
                {{ form.password2.errors }}
            </div>
        </div>
        <button type="submit" name="submit" class="btn send-btn">Register</button>
    </form>
</div><!--end leave comment-->
{% endblock %}

accounts/templates/accounts/user_form.html
{% extends "blog/base.html" %}
{% load bootstrap3 %}

{% block title %}Update user info{% endblock %}

{% block content %}
<h3>Update User Info</h3>
<form action="" method="post" class="form" role="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-success">Update</button>
</form>
{% endblock %}

accounts/templates/accounts/user_posts.html
{% extends "blog/base.html" %}
{% load bootstrap3 %}

{% block title %}My Posts{% endblock %}

{% block content %}
<h3>My Posts</h3>
    {% if request.user.post_set.all %}
        <table class="table table-bordered table-hover">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Title</th>
                    <th><span class="glyphicon glyphicon-eye-open"></span></th>
                    <th><span class="glyphicon glyphicon-comment"></span></th>
                    <th><span class="glyphicon glyphicon-thumbs-up"></span></th>
                    <th><span class="glyphicon glyphicon-thumbs-down"></span></th>
                    <th><span class="glyphicon glyphicon-star"></span></th>
                    <th>Update</th>
                    <th>Delete</th>
                </tr>
            </thead>
            <tbody>
            {% for post in request.user.post_set.all %}
                <tr>
                    <td>{{ post.id }}</td>
                    <td><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></td>
                    <td>{{ post.views }}</td>
                    <td>{{ post.comments }}</td>
                    <td>{{ post.likes }}</td>
                    <td>{{ post.dislikes }}</td>
                    <td>{{ post.rating }}</td>
                    <td><a href="{% url 'blog:post_update' post.id %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
                    <td>
                      <a data-toggle="modal" data-target="#postDelete"><span class="glyphicon glyphicon-trash"></span></a>
                      <!-- Modal-->
                      <div class="modal fade" id="postDelete" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">

                        <div class="modal-dialog">
                          <div class="modal-content">
                            
                            <div class="modal-header">
                              <button class="close" type="button" data-dismiss="modal" aria-hidden="true">&times;</button>
                              <h4 class="modal-title" id="myModalLabel">Are you sure?</h4>
                            </div>

                            <div class="modal-body">
                              You're about to delete {{ post.title }}. Please confirm.
                            </div>

                            <div class="modal-footer">
                              <form action="{% url 'blog:post_delete' post.id %}" method="post" role="form" class="from">
                                {% csrf_token %}
                                <button class="btn btn-default" type="button" data-dismiss="modal">Cancel</button>
                                <button class="btn btn-danger" type="submit">Delete</button>
                              </form>
                            </div>

                          </div> <!-- /.modal-content -->
                        </div> <!-- /.modal-dialog -->

                      </div> <!-- /.modal -->
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    {% else %}
        <br>
        <div class="panel panel-info">
            <div class="panel-heading">
                You do not have any posts!
            </div>
        </div>
    {% endif %}
        <a href="{% url 'blog:post_create' %}" class="btn btn-success">Create</a>
{% endblock %}