blog/urls.py
from django.urls import path

from .views import (
    PostListView,
    PostByCommentsListView,
    PostByLastCommentListView,
    PostByViewsListView,
    PostByRatingListView,
    PostDetailView,
    PostLikeRedirectView,
    PostDislikeRedirectView,
    CommentCreateView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    TagCreateView,
    TagListView,
    PostByTagListView
    )

app_name = 'blog'

urlpatterns = [
    path(''                             , PostListView.as_view()           , name='index'),
    path('most-commented/'              , PostByCommentsListView.as_view() , name='most_commented'),
    path('last-commented/'              , PostByLastCommentListView.as_view(), name='last_commented'),
    path('most-viewed/'                 , PostByViewsListView.as_view()    , name='most_viewed'),
    path('rating/'                      , PostByRatingListView.as_view()   , name='rating'),
    path('post/add/'                    , PostCreateView.as_view()         , name='post_create'),
    path('post/<slug:slug>/'            , PostDetailView.as_view()         , name='post_detail'),
    path('post/<slug:slug>/update/'     , PostUpdateView.as_view()         , name='post_update'),
    path('post/<slug:slug>/delete/'     , PostDeleteView.as_view()         , name='post_delete'),
    path('post/<slug:slug>/like/'       , PostLikeRedirectView.as_view()   , name='post_like'),
    path('post/<slug:slug>/dislike/'    , PostDislikeRedirectView.as_view(), name='post_dislike'),
    path('post/<slug:slug>/comment/add/', CommentCreateView.as_view()      , name='comment_add'),
    # path('tag/'                         , TagListView.as_view()            , name='tags'),
    # path('tag/add/'                     , TagCreateView.as_view()          , name='tag_add'),
    path('tag/<slug:slug>/'             , PostByTagListView.as_view()      , name='tag_detail'),
]

simpleblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(''         , include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/'   , admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

from pytils.translit import slugify


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    pub_date = models.DateTimeField('publication date', auto_now_add=True)
    upd_date = models.DateTimeField('update date', auto_now=True)
    text = models.TextField()
    comments = models.PositiveSmallIntegerField(default=0)
    last_comment_date = models.DateTimeField(default=datetime(1,1,1,0,0))
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveSmallIntegerField(default=0)
    dislikes = models.PositiveSmallIntegerField(default=0)
    rating = models.SmallIntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    tags = models.ManyToManyField('Tag')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True, verbose_name='Фото')
    slug = models.SlugField(unique=True)

    class Meta:
        db_table = 'posts'
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        ordering = ['-upd_date']

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.rating = self.likes - self.dislikes
        super().save(*args, **kwargs)

    def __str__(self):
        return '{} by {}'.format(self.title[:15], self.author)

    def get_image(self):
        if self.photo:
            return self.photo.url
        else:
            return 'https://fakeimg.pl/300x200/?text=Fake%20Img&font=lobster'


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    pub_date = models.DateTimeField('publication date', auto_now_add=True)
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        db_table = 'comments'
        ordering = ['-pub_date']

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.post.id})

    def __str__(self):
        return '{} by {}'.format(self.text[:15], self.author)


class Tag(models.Model):
    DEFAULT = 'default'
    PRIMARY = 'primary'
    SUCCESS = 'success'
    INFO = 'info'
    WARNING = 'warning'
    DANGER = 'danger'
    TAG_COLOR_CHOICES = (
        (DEFAULT, 'White'),
        (PRIMARY, 'Blue'),
        (SUCCESS, 'Green'),
        (INFO, 'Light blue'),
        (WARNING, 'Yellow'),
        (DANGER, 'Red')
    )
    color = models.CharField(max_length=10,
                             choices=TAG_COLOR_CHOICES,
                             default=DEFAULT)
    title = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(unique=True)

    class Meta:
        db_table = 'tags'
        ordering = ['title']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.title)


class View(models.Model):
    remote_addr = models.CharField(max_length=20)
    date_viewed = models.DateField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        db_table = 'views'

    def __str__(self):
        return '{} on {} from {}'.format(self.post, self.remote_addr, self.date_viewed)


class Button(models.Model):
    is_liked = models.BooleanField()
    is_disliked = models.BooleanField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'buttons'

    def __str__(self):
        return '{} to {}'.format(self.user, self.post.title[:15])

blog/forms.py
from django.forms import ModelForm, Textarea

from .models import Post, Comment, Tag


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': '', }
        widgets = {
            'text': Textarea(attrs={
                'cols': 20,
                'rows': 3,
                'placeholder': 'Add a public commint...'
            }),
        }


class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'tags', 'text']
        widgets = {'text': Textarea(attrs={'cols': 20, 'rows': 5}), }


class TagForm(ModelForm):

    class Meta:
        model = Tag
        fields = ['title', 'color']

blog/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import F, Q
from django.views.generic import (
    RedirectView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
    )
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy

from .models import Post, Comment, Tag, View, Button
from .forms import CommentForm, PostForm, TagForm


class PostListView(ListView):
    template_name = 'blog/post_list.html'
    paginate_by = 2
    context_object_name = 'post_list'

    def get_queryset(self):
        self.posts = Post.objects.all()
        self.query = self.request.GET.get('q')
        if self.query:
            self.posts = self.posts.filter(
                Q(title__icontains=self.query) |
                Q(text__icontains=self.query)
            )

        return self.posts.order_by('-upd_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.query
        return context


class PostByTagListView(ListView):
    template_name = 'blog/post_grid.html'
    context_object_name = 'post_list'
    paginate_by = 2

    def get_queryset(self):
        self.tag = get_object_or_404(Tag, slug=self.kwargs['slug'])
        self.post_list = self.tag.post_set.all()
        return self.post_list


class PostByCommentsListView(ListView):
    queryset = Post.objects.order_by('-comments')[:10]
    template_name = 'blog/post_list.html'
    context_object_name = 'post_list'


class PostByLastCommentListView(ListView):
    queryset = Post.objects.order_by('-last_comment_date')[:10]
    template_name = 'blog/post_list.html'
    context_object_name = 'post_list'


class PostByViewsListView(ListView):
    queryset = Post.objects.order_by('-views')[:10]
    template_name = 'blog/post_list.html'
    context_object_name = 'post_list'


class PostByRatingListView(ListView):
    queryset = Post.objects.order_by('-rating')[:10]


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    form_class = CommentForm

    def get_object(self):
        object = super().get_object()
        created = View.objects.get_or_create(
            post=object,
            remote_addr=self.request.META['REMOTE_ADDR']
        )[1]
        if created:
            object.views += 1
            object.save()

        return object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class
        return context


class PostLikeRedirectView(LoginRequiredMixin, RedirectView):
    pattern_name = 'blog:post_detail'

    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        user = self.request.user
        obj, created = Button.objects.get_or_create(post=post, user=user,
            defaults={'is_liked': True, 'is_disliked': False})
        
        if created:
            post.likes = F('likes') + 1
            messages.success(self.request, 'Added likes')
        else:
            if obj.is_liked and not obj.is_disliked:
                obj.is_liked = False
                post.likes = F('likes') - 1
                messages.success(self.request, 'Minus likes')
            
            elif not obj.is_liked and not obj.is_disliked:
                obj.is_liked = True
                post.likes = F('likes') + 1
                messages.success(self.request, 'Added likes')

            elif not obj.is_liked and obj.is_disliked:
                obj.is_liked = True
                post.likes = F('likes') + 1
                obj.is_disliked = False
                post.dislikes = F('dislikes') - 1
                messages.success(self.request, 'Added likes and minus dislike')

        obj.save()
        post.save()
        return super().get_redirect_url(*args, **kwargs)


class PostDislikeRedirectView(LoginRequiredMixin, RedirectView):
    pattern_name = 'blog:post_detail'

    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        user = self.request.user
        obj, created = Button.objects.get_or_create(post=post, user=user,
            defaults={'is_liked': False, 'is_disliked': True})
        if created:
            post.dislikes = F('dislikes') + 1
            messages.success(self.request, 'Add dislike')
        else:
            if obj.is_liked and not obj.is_disliked:
                obj.is_liked = False
                post.likes = F('likes') - 1
                obj.is_disliked = True
                post.dislikes = F('dislikes') + 1
                messages.success(self.request, 'Add dislike and minus like')

            elif not obj.is_liked and not obj.is_disliked:
                obj.is_disliked = True
                post.dislikes = F('dislikes') + 1
                messages.success(self.request, 'Add dislike')

            elif not obj.is_liked and obj.is_disliked:
                obj.is_disliked = False
                post.dislikes = F('dislikes') - 1
                messages.success(self.request, 'Minus dislike')
        
        obj.save()
        post.save()
        return super().get_redirect_url(*args, **kwargs)


class CommentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Comment
    form_class = CommentForm
    success_message = 'Comment created.'

    def get_queryset(self):
        self.post = get_object_or_404(Post, pk=self.kwargs['pk'])
        return self.post

    def form_valid(self, form):
        form.instance.post = self.get_queryset()
        form.instance.author = self.request.user
        self.post.comments += 1
        self.post.last_comment_date = datetime.now()
        self.post.save()
        return super().form_valid(form)


class PostCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name_suffix = '_create'
    success_url = reverse_lazy('accounts:posts')
    success_message = 'Post created'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name_suffix = '_update'
    success_url = reverse_lazy('accounts:posts')
    success_message = 'Post updated'

    def test_func(self):
        post_to_update = get_object_or_404(Post, pk=self.kwargs['pk'])
        return self.request.user == post_to_update.author
        

class PostDeleteView(UserPassesTestMixin, RedirectView):

    def get_queryset(self):
        return get_object_or_404(Post, pk=self.kwargs['pk'])

    def test_func(self):
        return self.request.user == self.get_queryset().author
    
    def post(self, request, *args, **kwargs):
        self.get_queryset().delete()
        messages.success(request, 'Post deleted')
        return super().post(request, *args, **kwargs)
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse('accounts:posts')


class TagListView(ListView):
    model = Tag
    

class TagCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy('blog:tags')
    success_message = 'Tag created'

blog/templates/blog/_post_detail.html
{% extends "blog/layouts/base.html" %}
{% load bootstrap3 %}
{% load static %}

{% block title %}{{ post.title|capfirst }}{% endblock %}

{% block content %}
  <h3>{{ post.title|capfirst }}</h3>
  <h5><span class="glyphicon glyphicon-time"></span> Post by {{ post.author|title }}, {{ post.upd_date|date:"M d, Y" }}</h5>
  
  {% for tag in post.tags.all %}
    <a href="{% url 'blog:tag_detail' tag.slug %}" class="btn btn-{{ tag.color }} btn-xs">{{ tag.title }}</a>
  {% endfor %}
  
  <br><br>

  <p>{{ post.text }}</p>
  <br>
  <h4>
    <span class="glyphicon glyphicon-eye-open"></span> {{ post.views }}
    &nbsp;&nbsp;
    <a href="{% url 'blog:post_like' post.slug %}" style="text-decoration: none;">
      <span class="glyphicon glyphicon-thumbs-up"></span> {{ post.likes|default:"LIKE" }}
    </a>
    &nbsp;&nbsp;
    <a href="{% url 'blog:post_dislike' post.slug %}" style="text-decoration: none;">
      <span class="glyphicon glyphicon-thumbs-down"></span> {{ post.dislikes|default:"DISLIKE" }}
    </a>
    &nbsp;&nbsp;
    <span class="glyphicon glyphicon-star"></span> {{ post.rating }}
  </h4>
  <hr>
  <h4>{{ post.comments }} Comments</h4>
  <form action="{% url 'blog:comment_add' post.slug %}" method="post" class="form" role="form">
    {% csrf_token %}
    {% bootstrap_form form %}
    <button type="submit" class="btn btn-success">Submit</button>
  </form>
  
  <br><br>
      
  <div class="row">
    {% for comment in post.comment_set.all %}
      <div class="col-sm-2 text-center">
        <img src="{% static 'img/avatar-tiny.jpg' %}" class="img-circle" height="65" width="65" alt="Avatar">
      </div>
      <div class="col-sm-10">
        <h4>{{ comment.author|title }} <small>{{ comment.pub_date|date:"M d, Y, P" }}</small></h4>
        <p>{{ comment.text }}</p>
        <br>
      </div>
    {% endfor %}
  </div>
{% endblock %}

blog/templates/blog/post_create.html
{% extends "blog/base.html" %}
{% load bootstrap3 %}

{% block title %}Create Post{% endblock %}

{% block content %}
<h3>Create Post</h3>
<a href="{% url 'blog:tag_add' %}" target="_blank" class="btn btn-link">Add tag</a>
<form action="" method="post" class="form" role="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-success">Create</button>
</form>
{% endblock %}

blog/templates/blog/post_detail.html
{% extends 'blog/layouts/base.html' %}

{% block title %}{{ post.title|capfirst }}{% endblock %}

{% block content %}
<article class="post">
    <div class="post-thumb">
        <img src="{{ post.get_image }}" alt="{{ post.title }}">
    </div>
    <div class="post-content">
        <header class="entry-header text-center text-uppercase">
            <h6><a href="#"> Travel</a></h6>
            <h1 class="entry-title">{{ post.title|capfirst }}</h1>
        </header>
        <div class="entry-content">{{ post.text }}</div>
        <div class="decoration">
            {% for tag in post.tags.all %}
                <a href="{% url 'blog:tag_detail' tag.slug %}" class="btn btn-default">{{ tag.title }}</a>
            {% endfor %}
        </div>
        <div class="social-share">
            <span class="social-share-title pull-left text-capitalize">By {{ post.author|title }} On {{ post.upd_date|date:"M d, Y" }}</span>
            <ul class="text-center pull-right">
                <li><a class="s-facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                <li><a class="s-twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a class="s-google-plus" href="#"><i class="fa fa-google-plus"></i></a></li>
                <li><a class="s-linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                <li><a class="s-instagram" href="#"><i class="fa fa-instagram"></i></a></li>
            </ul>
        </div>
    </div>
</article>
<div class="top-comment"><!--top comment-->
    <img src="assets/images/comment.jpg" class="pull-left img-circle" alt="">
    <h4>{{ post.author|title }}</h4>
    <p>Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy hello ro mod tempor
        invidunt ut labore et dolore magna aliquyam erat.</p>
</div><!--top comment end-->
<div class="row"><!--blog next previous-->
    <div class="col-md-6">
        <div class="single-blog-box">
            <a href="#">
                <img src="assets/images/blog-next.jpg" alt="">

                <div class="overlay">

                    <div class="promo-text">
                        <p><i class=" pull-left fa fa-angle-left"></i></p>
                        <h5>Rubel is doing Cherry theme</h5>
                    </div>
                </div>


            </a>
        </div>
    </div>
    <div class="col-md-6">
        <div class="single-blog-box">
            <a href="#">
                <img src="assets/images/blog-next.jpg" alt="">

                <div class="overlay">
                    <div class="promo-text">
                        <p><i class=" pull-right fa fa-angle-right"></i></p>
                        <h5>Rubel is doing Cherry theme</h5>

                    </div>
                </div>
            </a>
        </div>
    </div>
</div><!--blog next previous end-->
<div class="related-post-carousel"><!--related post carousel-->
    <div class="related-heading">
        <h4>You might also like</h4>
    </div>
    <div class="items">
        <div class="single-item">
            <a href="#">
                <img src="assets/images/related-post-1.jpg" alt="">

                <p>Just Wondering at Beach</p>
            </a>
        </div>


        <div class="single-item">
            <a href="#">
                <img src="assets/images/related-post-2.jpg" alt="">

                <p>Just Wondering at Beach</p>
            </a>
        </div>


        <div class="single-item">
            <a href="#">
                <img src="assets/images/related-post-3.jpg" alt="">

                <p>Just Wondering at Beach</p>
            </a>
        </div>


        <div class="single-item">
            <a href="#">
                <img src="assets/images/related-post-1.jpg" alt="">

                <p>Just Wondering at Beach</p>
            </a>
        </div>

        <div class="single-item">
            <a href="#">
                <img src="assets/images/related-post-2.jpg" alt="">

                <p>Just Wondering at Beach</p>
            </a>
        </div>


        <div class="single-item">
            <a href="#">
                <img src="assets/images/related-post-3.jpg" alt="">

                <p>Just Wondering at Beach</p>
            </a>
        </div>
    </div>
</div><!--related post carousel-->
<div class="bottom-comment"><!--bottom comment-->
    <h4>3 comments</h4>

    <div class="comment-img">
        <img class="img-circle" src="assets/images/comment-img.jpg" alt="">
    </div>

    <div class="comment-text">
        <a href="#" class="replay btn pull-right"> Replay</a>
        <h5>Rubel Miah</h5>

        <p class="comment-date">
            December, 02, 2015 at 5:57 PM
        </p>


        <p class="para">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed
            diam nonumy
            eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam
            voluptua. At vero eos et cusam et justo duo dolores et ea rebum.</p>
    </div>
</div>
<!-- end bottom comment-->


<div class="leave-comment"><!--leave comment-->
    <h4>Leave a reply</h4>


    <form class="form-horizontal contact-form" role="form" method="post" action="#">
        <div class="form-group">
            <div class="col-md-6">
                <input type="text" class="form-control" id="name" name="name" placeholder="Name">
            </div>
            <div class="col-md-6">
                <input type="email" class="form-control" id="email" name="email"
                        placeholder="Email">
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-12">
                <input type="text" class="form-control" id="subject" name="subject"
                        placeholder="Website url">
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-12">
                        <textarea class="form-control" rows="6" name="message"
                                    placeholder="Write Massage"></textarea>
            </div>
        </div>
        <a href="#" class="btn send-btn">Post Comment</a>
    </form>
</div><!--end leave comment-->



{% endblock %}

blog/templates/blog/post_grid.html
{% extends "blog/layouts/base.html" %}

{% block title %}Simple Blog{% endblock %}

{% block content %}
    {% if post_list.count > 0 %}
        <div class="row">
        {% for post in post_list %}
            <div class="col-md-6">
                <article class="post post-grid">
                    <div class="post-thumb">
                        <a href="{{ post.get_absolute_url }}"><img src="{{ post.get_image }}" alt=""></a>
                        <a href="{{ post.get_absolute_url }}" class="post-thumb-overlay text-center">
                            <div class="text-uppercase text-center">View Post</div>
                        </a>
                    </div>
                    <div class="post-content">
                        <header class="entry-header text-center text-uppercase">
                            <h6><a href="#"> Travel</a></h6>
                            <h2 class="entry-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h2>
                        </header>
                        <div class="entry-content">
                            <p>{{ post.text|safe|truncatewords:50 }}</p>
                            <div class="social-share">
                                <span class="social-share-title pull-left text-capitalize">By <a href="#">{{ post.author|title }}</a> On {{ post.upd_date|date:"M d, Y" }}</span>
                            </div>
                        </div>
                    </div>
                </article>
            </div>
        {% endfor %}
        </div>
        {% include 'blog/layouts/pagination.html' %}
    {% else %}
        <div class="panel panel-info">
            <div class="panel-heading">
                <h4>List of Posts is Empty!</h4>
            </div>
        </div>
    {% endif %}

{% endblock %}

blog/templates/blog/post_list.html
{% extends "blog/layouts/base.html" %}

{% block title %}Simple Blog{% endblock %}

{% block content %}
    {% if post_list.count > 0 %}
        {% for post in post_list %}
            <article class="post">
                <div class="post-thumb">
                    <a href="{{ post.get_absolute_url }}"><img src="{{ post.get_image }}" alt=""></a>
                    <a href="{{ post.get_absolute_url }}" class="post-thumb-overlay text-center">
                        <div class="text-uppercase text-center">View Post</div>
                    </a>
                </div>
                <div class="post-content">
                    <header class="entry-header text-center text-uppercase">
                        <h6><a href="#"> Travel</a></h6>
                        <h1 class="entry-title"><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h1>
                    </header>
                    <div class="entry-content">
                        <p>{{ post.text|safe|truncatewords:50 }}</p>
                        <div class="btn-continue-reading text-center text-uppercase">
                            <a href="{{ post.get_absolute_url }}" class="more-link">Continue Reading</a>
                        </div>
                    </div>
                    <div class="social-share">
                        <span class="social-share-title pull-left text-capitalize">By <a href="#">{{ post.author|title }}</a> On {{ post.upd_date|date:"M d, Y" }}</span>
                        <ul class="text-center pull-right">
                            <li><a class="s-facebook" href="#"><i class="fa fa-facebook"></i></a></li>
                            <li><a class="s-twitter" href="#"><i class="fa fa-twitter"></i></a></li>
                            <li><a class="s-google-plus" href="#"><i class="fa fa-google-plus"></i></a></li>
                            <li><a class="s-linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
                            <li><a class="s-instagram" href="#"><i class="fa fa-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
            </article>
        {% endfor %}

        {% include 'blog/layouts/pagination.html' %}
    {% else %}
        <div class="panel panel-info">
            <div class="panel-heading">
                <h4>List of Posts is Empty!</h4>
            </div>
        </div>
    {% endif %}

      {% comment %} <h4><small>RECENT POSTS</small></h4>
      <hr>
      <h2><a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a></h2>
      <h5><span class="glyphicon glyphicon-time"></span> Post by {{ post.author|title }}, {{ post.upd_date|date:"M d, Y" }}</h5>
      <br><br>
      <p>{{ post.text }}</p>
      <br>
      <h4>
        <span class="glyphicon glyphicon-eye-open"></span> {{ post.views }}&nbsp;&nbsp;
        <span class="glyphicon glyphicon-thumbs-up"></span> {{ post.likes }}&nbsp;&nbsp;
        <span class="glyphicon glyphicon-thumbs-down"></span> {{ post.dislikes }}&nbsp;&nbsp;
        <span class="glyphicon glyphicon-star"></span> {{ post.rating }}&nbsp;&nbsp;
        <span class="glyphicon glyphicon-comment"></span> {{ post.comments }}&nbsp;&nbsp;
        {% if post.comment_set.all %}
          <i>Last comment: {{ post.comment_set.first.pub_date|date:"M d, Y, P" }} by <b>{{ post.comment_set.first.author }}</b> {{ post.comment_set.first.text|truncatechars:50 }}</i>
        {% endif %}
      </h4> {% endcomment %}
    
{% endblock %}

blog/templates/blog/post_update.html
{% extends "blog/base.html" %}
{% load bootstrap3 %}

{% block title %}Update Post{% endblock %}

{% block content %}
<h3>Update Post</h3>
<a href="{% url 'blog:tag_add' %}" target="_blank" class="btn btn-link">Add tag</a>
<form action="" method="post" class="form" role="form">
  {% csrf_token %}
  {% bootstrap_form form %}
  <button type="submit" class="btn btn-success">Update</button>
</form>
{% endblock %}