accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from .views import (
    LoginView,
    LogoutView,
    PasswordChangeView,
    RegisterFormView,
    UserProfileView,
    UserPostsView,
    UserUpdateView,
    UserDeleteView,
    )

app_name = 'accounts'

urlpatterns = [
    path('login/'                  , LoginView.as_view()          , name='login'),
    path('logout/'                 , LogoutView.as_view()         , name='logout'),
    path('register/'               , RegisterFormView.as_view()   , name='register'),
    path('profile/'                , UserProfileView.as_view()    , name='profile'),
    path('profile/change-password/', PasswordChangeView.as_view() , name='change_password'),
    path('profile/update/'         , UserUpdateView.as_view()     , name='update'),
    path('profile/delete/'         , UserDeleteView.as_view()     , name='delete'),
    path('posts/'                  , UserPostsView.as_view()      , name='posts'),
]

blog/urls.py
from django.urls import path

from .views import (
    PostListView,
    PostByCommentsListView,
    PostByLastCommentListView,
    PostByViewsListView,
    PostByRatingListView,
    PostDetailView,
    PostLikeRedirectView,
    PostDislikeRedirectView,
    CommentCreateView,
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    TagCreateView,
    TagListView,
    PostByTagListView
    )

app_name = 'blog'

urlpatterns = [
    path(''                             , PostListView.as_view()           , name='index'),
    path('most-commented/'              , PostByCommentsListView.as_view() , name='most_commented'),
    path('last-commented/'              , PostByLastCommentListView.as_view(), name='last_commented'),
    path('most-viewed/'                 , PostByViewsListView.as_view()    , name='most_viewed'),
    path('rating/'                      , PostByRatingListView.as_view()   , name='rating'),
    path('post/add/'                    , PostCreateView.as_view()         , name='post_create'),
    path('post/<slug:slug>/'            , PostDetailView.as_view()         , name='post_detail'),
    path('post/<slug:slug>/update/'     , PostUpdateView.as_view()         , name='post_update'),
    path('post/<slug:slug>/delete/'     , PostDeleteView.as_view()         , name='post_delete'),
    path('post/<slug:slug>/like/'       , PostLikeRedirectView.as_view()   , name='post_like'),
    path('post/<slug:slug>/dislike/'    , PostDislikeRedirectView.as_view(), name='post_dislike'),
    path('post/<slug:slug>/comment/add/', CommentCreateView.as_view()      , name='comment_add'),
    # path('tag/'                         , TagListView.as_view()            , name='tags'),
    # path('tag/add/'                     , TagCreateView.as_view()          , name='tag_add'),
    path('tag/<slug:slug>/'             , PostByTagListView.as_view()      , name='tag_detail'),
]

simpleblog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path(''         , include('blog.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/'   , admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from datetime import datetime

from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import slugify
from django.urls import reverse

from pytils.translit import slugify


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    pub_date = models.DateTimeField('publication date', auto_now_add=True)
    upd_date = models.DateTimeField('update date', auto_now=True)
    text = models.TextField()
    comments = models.PositiveSmallIntegerField(default=0)
    last_comment_date = models.DateTimeField(default=datetime(1,1,1,0,0))
    views = models.PositiveIntegerField(default=0)
    likes = models.PositiveSmallIntegerField(default=0)
    dislikes = models.PositiveSmallIntegerField(default=0)
    rating = models.SmallIntegerField(default=0)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    tags = models.ManyToManyField('Tag')
    photo = models.ImageField(upload_to='photos/%Y/%m/%d', blank=True, verbose_name='Фото')
    slug = models.SlugField(unique=True)

    class Meta:
        db_table = 'posts'
        verbose_name = 'Запись'
        verbose_name_plural = 'Записи'
        ordering = ['-upd_date']

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'slug': self.slug})

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        self.rating = self.likes - self.dislikes
        super().save(*args, **kwargs)

    def __str__(self):
        return '{} by {}'.format(self.title[:15], self.author)

    def get_image(self):
        if self.photo:
            return self.photo.url
        else:
            return 'https://fakeimg.pl/300x200/?text=Fake%20Img&font=lobster'


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    pub_date = models.DateTimeField('publication date', auto_now_add=True)
    text = models.TextField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        db_table = 'comments'
        ordering = ['-pub_date']

    def get_absolute_url(self):
        return reverse('blog:post_detail', kwargs={'pk': self.post.id})

    def __str__(self):
        return '{} by {}'.format(self.text[:15], self.author)


class Tag(models.Model):
    DEFAULT = 'default'
    PRIMARY = 'primary'
    SUCCESS = 'success'
    INFO = 'info'
    WARNING = 'warning'
    DANGER = 'danger'
    TAG_COLOR_CHOICES = (
        (DEFAULT, 'White'),
        (PRIMARY, 'Blue'),
        (SUCCESS, 'Green'),
        (INFO, 'Light blue'),
        (WARNING, 'Yellow'),
        (DANGER, 'Red')
    )
    color = models.CharField(max_length=10,
                             choices=TAG_COLOR_CHOICES,
                             default=DEFAULT)
    title = models.CharField(max_length=20, unique=True)
    slug = models.SlugField(unique=True)

    class Meta:
        db_table = 'tags'
        ordering = ['title']

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def __str__(self):
        return '{}'.format(self.title)


class View(models.Model):
    remote_addr = models.CharField(max_length=20)
    date_viewed = models.DateField(auto_now_add=True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    class Meta:
        db_table = 'views'

    def __str__(self):
        return '{} on {} from {}'.format(self.post, self.remote_addr, self.date_viewed)


class Button(models.Model):
    is_liked = models.BooleanField()
    is_disliked = models.BooleanField()
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'buttons'

    def __str__(self):
        return '{} to {}'.format(self.user, self.post.title[:15])

blog/forms.py
from django.forms import ModelForm, Textarea

from .models import Post, Comment, Tag


class CommentForm(ModelForm):

    class Meta:
        model = Comment
        fields = ['text']
        labels = {'text': '', }
        widgets = {
            'text': Textarea(attrs={
                'cols': 20,
                'rows': 3,
                'placeholder': 'Add a public commint...'
            }),
        }


class PostForm(ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'tags', 'text']
        widgets = {'text': Textarea(attrs={'cols': 20, 'rows': 5}), }


class TagForm(ModelForm):

    class Meta:
        model = Tag
        fields = ['title', 'color']

blog/views.py
from datetime import datetime

from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import F, Q
from django.views.generic import (
    RedirectView,
    ListView,
    DetailView,
    CreateView,
    UpdateView,
    DeleteView
    )
from django.shortcuts import redirect, get_object_or_404
from django.urls import reverse, reverse_lazy

from .models import Post, Comment, Tag, View, Button
from .forms import CommentForm, PostForm, TagForm


class PostListView(ListView):
    template_name = 'blog/post_list.html'
    paginate_by = 2
    context_object_name = 'post_list'

    def get_queryset(self):
        self.posts = Post.objects.all()
        self.query = self.request.GET.get('q')
        if self.query:
            self.posts = self.posts.filter(
                Q(title__icontains=self.query) |
                Q(text__icontains=self.query)
            )

        return self.posts.order_by('-upd_date')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['query'] = self.query
        return context


class PostByTagListView(ListView):
    template_name = 'blog/post_grid.html'
    context_object_name = 'post_list'
    paginate_by = 2

    def get_queryset(self):
        self.tag = get_object_or_404(Tag, slug=self.kwargs['slug'])
        self.post_list = self.tag.post_set.all()
        return self.post_list


class PostByCommentsListView(ListView):
    queryset = Post.objects.order_by('-comments')[:10]
    template_name = 'blog/post_list.html'
    context_object_name = 'post_list'


class PostByLastCommentListView(ListView):
    queryset = Post.objects.order_by('-last_comment_date')[:10]
    template_name = 'blog/post_list.html'
    context_object_name = 'post_list'


class PostByViewsListView(ListView):
    queryset = Post.objects.order_by('-views')[:10]
    template_name = 'blog/post_list.html'
    context_object_name = 'post_list'


class PostByRatingListView(ListView):
    queryset = Post.objects.order_by('-rating')[:10]


class PostDetailView(DetailView):
    model = Post
    context_object_name = 'post'
    form_class = CommentForm

    def get_object(self):
        object = super().get_object()
        created = View.objects.get_or_create(
            post=object,
            remote_addr=self.request.META['REMOTE_ADDR']
        )[1]
        if created:
            object.views += 1
            object.save()

        return object

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.form_class
        return context


class PostLikeRedirectView(LoginRequiredMixin, RedirectView):
    pattern_name = 'blog:post_detail'

    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        user = self.request.user
        obj, created = Button.objects.get_or_create(post=post, user=user,
            defaults={'is_liked': True, 'is_disliked': False})
        
        if created:
            post.likes = F('likes') + 1
            messages.success(self.request, 'Added likes')
        else:
            if obj.is_liked and not obj.is_disliked:
                obj.is_liked = False
                post.likes = F('likes') - 1
                messages.success(self.request, 'Minus likes')
            
            elif not obj.is_liked and not obj.is_disliked:
                obj.is_liked = True
                post.likes = F('likes') + 1
                messages.success(self.request, 'Added likes')

            elif not obj.is_liked and obj.is_disliked:
                obj.is_liked = True
                post.likes = F('likes') + 1
                obj.is_disliked = False
                post.dislikes = F('dislikes') - 1
                messages.success(self.request, 'Added likes and minus dislike')

        obj.save()
        post.save()
        return super().get_redirect_url(*args, **kwargs)


class PostDislikeRedirectView(LoginRequiredMixin, RedirectView):
    pattern_name = 'blog:post_detail'

    def get_redirect_url(self, *args, **kwargs):
        post = get_object_or_404(Post, pk=self.kwargs['pk'])
        user = self.request.user
        obj, created = Button.objects.get_or_create(post=post, user=user,
            defaults={'is_liked': False, 'is_disliked': True})
        if created:
            post.dislikes = F('dislikes') + 1
            messages.success(self.request, 'Add dislike')
        else:
            if obj.is_liked and not obj.is_disliked:
                obj.is_liked = False
                post.likes = F('likes') - 1
                obj.is_disliked = True
                post.dislikes = F('dislikes') + 1
                messages.success(self.request, 'Add dislike and minus like')

            elif not obj.is_liked and not obj.is_disliked:
                obj.is_disliked = True
                post.dislikes = F('dislikes') + 1
                messages.success(self.request, 'Add dislike')

            elif not obj.is_liked and obj.is_disliked:
                obj.is_disliked = False
                post.dislikes = F('dislikes') - 1
                messages.success(self.request, 'Minus dislike')
        
        obj.save()
        post.save()
        return super().get_redirect_url(*args, **kwargs)


class CommentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Comment
    form_class = CommentForm
    success_message = 'Comment created.'

    def get_queryset(self):
        self.post = get_object_or_404(Post, pk=self.kwargs['pk'])
        return self.post

    def form_valid(self, form):
        form.instance.post = self.get_queryset()
        form.instance.author = self.request.user
        self.post.comments += 1
        self.post.last_comment_date = datetime.now()
        self.post.save()
        return super().form_valid(form)


class PostCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name_suffix = '_create'
    success_url = reverse_lazy('accounts:posts')
    success_message = 'Post created'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostUpdateView(UserPassesTestMixin, SuccessMessageMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name_suffix = '_update'
    success_url = reverse_lazy('accounts:posts')
    success_message = 'Post updated'

    def test_func(self):
        post_to_update = get_object_or_404(Post, pk=self.kwargs['pk'])
        return self.request.user == post_to_update.author
        

class PostDeleteView(UserPassesTestMixin, RedirectView):

    def get_queryset(self):
        return get_object_or_404(Post, pk=self.kwargs['pk'])

    def test_func(self):
        return self.request.user == self.get_queryset().author
    
    def post(self, request, *args, **kwargs):
        self.get_queryset().delete()
        messages.success(request, 'Post deleted')
        return super().post(request, *args, **kwargs)
    
    def get_redirect_url(self, *args, **kwargs):
        return reverse('accounts:posts')


class TagListView(ListView):
    model = Tag
    

class TagCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy('blog:tags')
    success_message = 'Tag created'

blog/templates/blog/layouts/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="{% static 'assets/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/animate.min.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.carousel.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.theme.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/owl.transitions.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">

    <!-- Favicon -->
    <link rel="icon" type="image/png" href="{% static 'assets/images/favicon.png' %}">

    <title>{% block title %}{% endblock %} | Simple Blog</title>
</head>
<body>

{% include 'blog/layouts/navbar.html' %}

<div class="main-content">
    <div class="container">
        <div class="row">
            <div class="col-md-8">
                {% block content %}{% endblock %}
            </div>
            <div class="col-md-4" data-sticky_column>
                {% include 'blog/layouts/sidebar.html' %}
            </div>
        </div>
    </div>
</div>

{% include 'blog/layouts/instagram.html' %}

{% include 'blog/layouts/footer.html' %}

<script type="text/javascript" src="{% static 'assets/js/jquery-1.11.3.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/bootstrap.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/owl.carousel.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/jquery.stickit.min.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/menu.js' %}"></script>
<script type="text/javascript" src="{% static 'assets/js/scripts.js' %}"></script>
</body>
</html>

blog/templates/blog/layouts/footer.html
<footer class="footer-widget-section">
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <aside class="footer-widget">
                    <div class="about-img"><img src="assets/images/footer-logo.png" alt=""></div>
                    <div class="about-content">Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy
                        eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed voluptua. At vero eos et
                        accusam et justo duo dlores et ea rebum magna text ar koto din.
                    </div>
                    <div class="address">
                        <h4 class="text-uppercase">contact Info</h4>

                        <p> 142/5 BC Street, ES, VSA</p>

                        <p> Phone: +123 456 78900</p>

                        <p>rahim@marlindev.ru</p>
                    </div>
                </aside>
            </div>

            <div class="col-md-4">
                <aside class="footer-widget">
                    <h3 class="widget-title text-uppercase">Testimonials</h3>

                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                        <!--Indicator-->
                        <ol class="carousel-indicators">
                            <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#myCarousel" data-slide-to="1"></li>
                            <li data-target="#myCarousel" data-slide-to="2"></li>
                        </ol>
                        <div class="carousel-inner" role="listbox">
                            <div class="item active">
                                <div class="single-review">
                                    <div class="review-text">
                                        <p>Lorem ipsum dolor sit amet, conssadipscing elitr, sed diam nonumy eirmod
                                            tempvidunt ut labore et dolore magna aliquyam erat,sed diam voluptua. At
                                            vero eos et accusam justo duo dolores et ea rebum.gubergren no sea takimata
                                            magna aliquyam eratma</p>
                                    </div>
                                    <div class="author-id">
                                        <img src="assets/images/author.png" alt="">

                                        <div class="author-text">
                                            <h4>Sophia</h4>

                                            <h4>Client, Tech</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="single-review">
                                    <div class="review-text">
                                        <p>Lorem ipsum dolor sit amet, conssadipscing elitr, sed diam nonumy eirmod
                                            tempvidunt ut labore et dolore magna aliquyam erat,sed diam voluptua. At
                                            vero eos et accusam justo duo dolores et ea rebum.gubergren no sea takimata
                                            magna aliquyam eratma</p>
                                    </div>
                                    <div class="author-id">
                                        <img src="assets/images/author.png" alt="">

                                        <div class="author-text">
                                            <h4>Sophia</h4>

                                            <h4>Client, Tech</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="item">
                                <div class="single-review">
                                    <div class="review-text">
                                        <p>Lorem ipsum dolor sit amet, conssadipscing elitr, sed diam nonumy eirmod
                                            tempvidunt ut labore et dolore magna aliquyam erat,sed diam voluptua. At
                                            vero eos et accusam justo duo dolores et ea rebum.gubergren no sea takimata
                                            magna aliquyam eratma</p>
                                    </div>
                                    <div class="author-id">
                                        <img src="assets/images/author.png" alt="">

                                        <div class="author-text">
                                            <h4>Sophia</h4>

                                            <h4>Client, Tech</h4>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                </aside>
            </div>
            <div class="col-md-4">
                <aside class="footer-widget">
                    <h3 class="widget-title text-uppercase">Custom Category Post</h3>


                    <div class="custom-post">
                        <div>
                            <a href="#"><img src="assets/images/footer-img.png" alt=""></a>
                        </div>
                        <div>
                            <a href="#" class="text-uppercase">Home is peaceful Place</a>
                            <span class="p-date">February 15, 2016</span>
                        </div>
                    </div>
                </aside>
            </div>
        </div>
    </div>
    <div class="footer-copy">
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="text-center">&copy; 2017 <a href="#">Blog, </a> Designed with <i
                            class="fa fa-heart"></i> by <a href="#">Marlin</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>

blog/templates/blog/layouts/instagram.html
{% load static %}
<div id="footer">
    <div class="footer-instagram-section">
        <h3 class="footer-instagram-title text-center text-uppercase">Instagram</h3>

        <div id="footer-instagram" class="owl-carousel">

            <div class="item">
                <a href="#"><img src="{% static 'assets/images/ins-1.jpg' %}" alt=""></a>
            </div>
            <div class="item">
                <a href="#"><img src="{% static 'assets/images/ins-2.jpg' %}" alt=""></a>
            </div>
            <div class="item">
                <a href="#"><img src="{% static 'assets/images/ins-3.jpg' %}" alt=""></a>
            </div>
            <div class="item">
                <a href="#"><img src="{% static 'assets/images/ins-4.jpg' %}" alt=""></a>
            </div>
            <div class="item">
                <a href="#"><img src="{% static 'assets/images/ins-5.jpg' %}" alt=""></a>
            </div>
            <div class="item">
                <a href="#"><img src="{% static 'assets/images/ins-6.jpg' %}" alt=""></a>
            </div>
            <div class="item">
                <a href="#"><img src="{% static 'assets/images/ins-7.jpg' %}" alt=""></a>
            </div>
            <div class="item">
                <a href="#"><img src="{% static 'assets/images/ins-8.jpg' %}" alt=""></a>
            </div>

        </div>
    </div>
</div>

blog/templates/blog/layouts/messages.html
{% if messages %}
    {% for message in messages %}
    <br>
    <div class="alert alert-{{ message.tags }} alert-dismissable fade in">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
        <strong>{{ message.tags|capfirst }}!</strong> {{ message }}
    </div>   
    {% endfor %}
{% endif %}

blog/templates/blog/layouts/navbar.html
<nav class="navbar main-menu navbar-default">
    <div class="container">
        <div class="menu-content">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'blog:index' %}"><img src="assets/images/logo.png" alt=""></a>
            </div>


            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

                <ul class="nav navbar-nav text-uppercase">
                    <li><a href="{% url 'blog:index' %}">Homepage</a></li>
                    <li><a href="#">ABOUT ME </a></li>
                    <li><a href="#">CONTACT</a></li>
                </ul>

                <ul class="nav navbar-nav text-uppercase pull-right">
                  {% if user.is_authenticated %}
                      <li><a href="{% url 'accounts:profile' %}">My profile</a></li>
                      <li><a href="{% url 'accounts:logout' %}">Logout</a></li>
                  {% else %}
                      <li><a href="{% url 'accounts:register' %}">Register</a></li>
                      <li><a href="{% url 'accounts:login' %}">Login</a></li>
                  {% endif %}
                </ul>

            </div>
            <!-- /.navbar-collapse -->

            <div class="show-search">
                <form role="search" method="get" id="searchform" action="{% url 'blog:index' %}">
                    <div>
                        <input name="q" type="text" placeholder="Search and hit enter..." name="s" value="{{ query|default:'' }}">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- /.container-fluid -->
</nav>

blog/templates/blog/layouts/pagination.html
{% if page_obj.has_other_pages %}
    <ul class="pagination">

        {% if page_obj.has_previous %}
            <li>
                <a href="?{{ s }}page={{ page_obj.previous_page_number }}">
                    <i class="fa fa-angle-double-left" aria-hidden="true"></i>
                </a>
            </li>
        {% endif %}

        {% for p in page_obj.paginator.page_range %}
            {% if page_obj.number == p %}
                <li class="active"><a href="#">{{ p }}</a></li>
            {% else %}
                <li><a href="?{{ s }}page={{ p }}">{{ p }}</a></li>
            {% endif %}
        {% endfor %}

        {% if page_obj.has_next %}
            <li>
                <a href="?{{ s }}page={{ page_obj.next_page_number }}">
                    <i class="fa fa-angle-double-right" aria-hidden="true"></i>
                </a>
            <li>
        {% endif %}

    </ul>
{% endif %}